//! Subprocess benchmark — launches a minimal x86 binary through runtime_loader
//! and measures throughput.
//!
//! Architecture:
//!   1. Generate a minimal x86 ASM file with the hot-path x87 instruction mix
//!   2. Assemble into a flat binary using `nasm`
//!   3. Launch via runtime_loader (rosettax87_jit's subprocess)
//!   4. Measure execution time / iterations per second
//!
//! Prerequisites: `nasm` must be installed (`brew install nasm`)

use std::process::Command;
use std::time::Instant;

pub fn find_runtime_loader() -> std::path::PathBuf {
    let candidates = [
        "vendor/rosettax87_jit/build/runtime_loader",
        "target/debug/runtime_loader",
        "target/release/runtime_loader",
    ];
    for candidate in candidates {
        let p = std::path::Path::new(candidate);
        if p.exists() {
            return p.to_path_buf();
        }
    }
    match which::which("runtime_loader") {
        Ok(p) => p,
        Err(_) => std::path::PathBuf::from("runtime_loader"),
    }
}

pub fn run_subprocess_benchmark(
    runtime_loader: &std::path::Path,
    asm_source: &str,
    iterations: usize,
) -> std::process::Output {
    let asm_path = std::env::temp_dir().join("hot_path_bench.asm");
    std::fs::write(&asm_path, asm_source).expect("failed to write ASM");

    let bin_path = std::env::temp_dir().join("hot_path_bench.bin");
    let assemble = Command::new("nasm")
        .args([
            "-f", "bin",
            &asm_path.to_string_lossy(),
            "-o", &bin_path.to_string_lossy(),
        ])
        .output()
        .expect("nasm not found — install with: brew install nasm");

    if !assemble.status.success() {
        eprintln!("ASM:\n{}", asm_source);
        eprintln!("nasm stderr: {}", String::from_utf8_lossy(&assemble.stderr));
        panic!("nasm assembly failed");
    }

    let start = Instant::now();
    let output = Command::new(runtime_loader)
        .arg(&bin_path)
        .arg(iterations.to_string())
        .output()
        .expect("runtime_loader failed to launch");
    let elapsed = start.elapsed();

    let ips = iterations as f64 / elapsed.as_secs_f64();
    println!(
        "runtime_loader: {} iterations in {:.3}s = {:.0} ips",
        iterations,
        elapsed.as_secs_f64(),
        ips,
    );

    output
}

pub fn generate_asm(instructions: &[crate::hot_path::InstructionWeight]) -> String {
    let mut lines = vec![
        "; Auto-generated hot-path benchmark assembly".to_string(),
        "; Generated by build_mre.py".to_string(),
        "section .text".to_string(),
        "global _start".to_string(),
        "_start:".to_string(),
        "    mov ecx, [esp+4]".to_string(),
        "    mov ebx, [esp+8]".to_string(),
        "    xor esi, esi".to_string(),
        "    jmp .check_loop".to_string(),
        ".loop:".to_string(),
    ];

    const SCALE: usize = 100;
    for inst in instructions {
        let count = (inst.weight * SCALE as f64).ceil() as usize;
        let bytes_repr: String = inst.bytes.iter().map(|b| format!("0x{:02X}", b)).collect::<Vec<_>>().join(", ");
        lines.push(format!("    ; {} (weight={:.3}, {} dispatches)", inst.opcode, inst.weight, count));
        for _ in 0..count.min(10) {
            lines.push(format!("    db {} ; {}", bytes_repr, inst.opcode));
        }
        if count > 10 {
            lines.push(format!("    ; ... +{} more reps", count - 10));
        }
    }

    lines.extend([
        "    inc esi".to_string(),
        ".check_loop:".to_string(),
        "    cmp esi, ebx".to_string(),
        "    jl .loop".to_string(),
        "    ret".to_string(),
    ]);

    lines.join("\n")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn find_runtime_loader_returns_path() {
        let loader = find_runtime_loader();
        assert!(!loader.as_os_str().is_empty(), "runtime_loader path should not be empty");
    }

    #[test]
    fn generate_asm_with_empty_instructions() {
        let asm = generate_asm(&[]);
        assert!(asm.contains("_start"), "should have entry point");
    }

    #[test]
    fn generate_asm_with_instructions() {
        use crate::hot_path::InstructionWeight;
        let instructions = vec![
            InstructionWeight { opcode: "fld", bytes: &[0xD9, 0x00], weight: 0.6, count: 600 },
            InstructionWeight { opcode: "fstp", bytes: &[0xDD, 0xD8], weight: 0.4, count: 400 },
        ];
        let asm = generate_asm(&instructions);
        assert!(asm.contains("0xD9"), "should emit x87 bytes");
        assert!(asm.contains("fld"), "should mention fld opcode");
        assert!(asm.contains("_start"), "should have entry point");
    }
}
