name: Build Verify

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-darwin

      - run: brew install zig

      - name: Build wowplay
        run: cargo build --release --target aarch64-apple-darwin -p wowplay

      - name: Build winerosetta.dll
        run: zig build --release=safe
        working-directory: packages/zig-glue
